variables:
  ConnectedServiceName: 'Primary'
  WebAppName: 'kraigb-flaskpipelines'

trigger:
- master

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

# Install the virtual environment on the build agent, which is then
# deployed with the app code.

- script: |
    python3.6 -m venv .env
    source .env/bin/activate
    pip3.6 install setuptools
    pip3.6 install -r requirements.txt

  # The displayName is shows in the pipeline UI when a build runs
  displayName: 'Install Dependencies'

- script: |
    echo Deleting venv
    rmdir -rf .env
  displayName: 'Remove .env before zip'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: # Optional

- task: AzureRMWebAppDeployment@4
  displayName: Azure App Service Deploy
  inputs:
    appType: webAppLinux
    RuntimeStack: 'PYTHON|3.6'
    ConnectedServiceName: $(ConnectedServiceName)
    WebAppName: $(WebAppName)
    Package: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    StartupCommand: 'gunicorn --bind=0.0.0.0 --workers=4 startup:app'

    # Inline post-deployment script
    ScriptType: Inline Script
    InlineScript:
      echo 'Add your inline script steps here'

    # Alternate form: refer to a script in the repository
    # ScriptType: File Path
    # ScriptPath: 'post-deployment.sh'

